### ISSUE TITLE
upsert endpoint falied with `AuthenticationError`

### ISSUE THREAD

**Issue by ocherry341** [openai/chatgpt-retrieval-plugin#107]
I've setup the project locally with redis datastore and starting the application

```
$ poetry run start
INFO:     Will watch for changes in these directories: ['E:\\code\\chatgpt-retrieval-plugin']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [14784] using StatReload
INFO:     Started server process [18672]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

When I post /upsert I got a RetryError
```
Error: RetryError[<Future at 0x1dfaf1e2140 state=finished raised AuthenticationError>]
INFO:     127.0.0.1:62070 - "POST /upsert HTTP/1.1" 500 Internal Server Error
```

My request Body is
```json
{
    "documents": [
        {
            "text": "Redis is a real-time data platform that supports a variety of use cases for everyday applications as well as AI/ML workloads. Use Redis as a low-latency vector engine by creating a Redis database with the Redis Stack docker container. For a hosted/managed solution, try Redis Cloud. See more helpful examples of Redis as a vector database here.The database needs the RediSearch module (>=v2.6) and RedisJSON, which are included in the self-hosted docker compose above.Run the App with the Redis docker image: docker compose up -d in this dir.The app automatically creates a Redis vector search index on the first run. Optionally, create a custom index with a specific name and set it as an environment variable (see below).To enable more hybrid searching capabilities, adjust the document schema here."
        }
    ]
}
```

My env
```
DATASTORE=redis
OPENAI_API_KEY=<MY_API_KEY>
```
The OPENAI_API_KEY is valid for accessing the OpenAI API. 
I don't have a BEARER_TOKEN because I'm using No Authentication Methods.

How can I get more information about the error?

**Comment by alvinhom** [comment]
Most likely the problem with the API key is incorrect.  I was encountering the same issue, then I realized I misspelled the environment variable as OPEN_API_KEY.  After changing it to OPENAI_API_KEY and putting in the right key, it was working.

**Comment by anirudhgarg** [comment]
> Most likely the problem with the API key is incorrect. I was encountering the same issue, then I realized I misspelled the environment variable as OPEN_API_KEY. After changing it to OPENAI_API_KEY and putting in the right key, it was working.

I had the same issue :)

**Comment by akrabulislam** [comment]
Same to me is there any solution? I am trying to access `pinecone`. The query API giving me the same error. My API key is valid

**Comment by kelvinchumbe** [comment]
@akrabulislam Did you find a fix for this? I'm using pinecone as well and I keep getting the same error although the API key is valid

**Comment by rodrigolearns** [comment]
Same in my case :/

**Comment by buddeshya** [comment]
I am getting the same error
`Error: RetryError[<Future at 0x11d681d80 state=finished raised AuthenticationError>]
INFO:     127.0.0.1:57535 - "POST /upsert HTTP/1.1" 500 Internal Server Error`

Has anyone found the solution?
I feel there might be a problem with setting a organizations key

```
openai.organization = "org-xTI25cOgl4eS0zYzuxTu1nlR"
openai.api_key = os.getenv("OPENAI_API_KEY")
```
Can anyone suggest how to set the organization key in CHATGPT RETRIVAL PLUGIN??

**Comment by Lawhacknifemi** [comment]
> @akrabulislam Did you find a fix for this? I'm using pinecone as well and I keep getting the same error although the API key is valid

Hey man did you find the fix?


> Same to me is there any solution? I am trying to access `pinecone`. The query API gave me the same error. My API key is valid

Hey man did you find the fix?

**Comment by ghmulchandani** [comment]
> I am getting the same error `Error: RetryError[<Future at 0x11d681d80 state=finished raised AuthenticationError>] INFO: 127.0.0.1:57535 - "POST /upsert HTTP/1.1" 500 Internal Server Error`
> 
> Has anyone found the solution? I feel there might be a problem with setting a organizations key
> 
> ```
> openai.organization = "org-xTI25cOgl4eS0zYzuxTu1nlR"
> openai.api_key = os.getenv("OPENAI_API_KEY")
> ```
> 
> Can anyone suggest how to set the organization key in CHATGPT RETRIVAL PLUGIN??

If you are using Windows use 
set OPENAI_API_KEY=<your_openai_api>

For Windows 
export OPENAI_API_KEY=<your_openai_api>
Orgnization key is optional if you have single organization in the account. 
It works for single organization account.
