### ISSUE TITLE
unclosed file

### ISSUE THREAD

**Issue by sbc-max** [openai/chatgpt-retrieval-plugin#109]
If the extract_text_from_file func fails for whatever reason (still investigating that issue) the file is left unclosed causing further errors. Suggest wrapping it in a with statement. 

https://github.com/openai/chatgpt-retrieval-plugin/blob/958bb787bf34823538482a9eb3157c5bf994a182/services/file.py#L38

**Comment by CristiVlad25** [comment]
```
def extract_text_from_file(filepath):
    try:
        with open(filepath, "rb") as file:
            # Your existing code for extracting text from the file
            # ...

    except Exception as e:
        # Handle the exception if needed
        # ..


```

**Comment by isafulf** [comment]
Good catch, thanks! e871ab4bee2266cabd5989f46c545a7f83323b17
