### ISSUE TITLE
Redis Datastore: TypeError: Logger._log() got an unexpected keyword argument 'flush'

### ISSUE THREAD

**Issue by blasscoc** [openai/chatgpt-retrieval-plugin#132]
Applying a query to a redis datastore I was getting a:
TypeError: Logger._log() got an unexpected keyword argument 'flush'

On line 318 of redis_datastore.py
        logging.info(f"Gathering {len(queries)} query results", flush=True)  # type: ignore

I removed it, seems fine.

**Comment by tylerhutcherson** [comment]
Fixing this now -- thanks
