### ISSUE TITLE
When Querying: WARNING: Invalid HTTP request received.

### ISSUE THREAD

**Issue by dbigham** [openai/chatgpt-retrieval-plugin#160]
After using the upsert endpoint to upload some text, I tried a query from the ChatGPT interface:

![image](https://user-images.githubusercontent.com/1895770/230701223-88b5f986-6291-48c9-973f-960eac29ea42.png)

The console shows:

`WARNING:  Invalid HTTP request received`

**Comment by dbigham** [comment]
Note that if I do what appears to be the same query via the /docs endpoint, it appears to work:

![image](https://user-images.githubusercontent.com/1895770/230701664-751bdba0-ab6c-41e3-9d1b-8301cd5ebb1b.png)

**Comment by simonMoisselin** [comment]
it's https issue 
Somehow openai is doing an https request instead of http (at least for me)
You can inspect queries in the browser inspector

**Comment by simonMoisselin** [comment]
Apparently this is fixed if you pull the latest

**Comment by simonMoisselin** [comment]
Try replacing localhost by 0.0.0.0

**Comment by dbigham** [comment]
I did a git pull today and tried the quickstart again, and now it seems to be working.
