### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'FT.CREATE'

### ISSUE THREAD

**Issue by GEEKROS** [openai/chatgpt-retrieval-plugin#17]
redis.exceptions.ResponseError: unknown command 'FT.CREATE'?

**Comment by alg-bug-engineer** [comment]
me too

**Comment by qichangc** [comment]
https://github.com/openai/chatgpt-retrieval-plugin#redis

**Comment by zscorpio** [comment]
```
docker run -p 6379:6379 redislabs/redisearch:latest
```
helps

**Comment by spursy** [comment]
> 

cannot salve my problem

**Comment by AbirKorched** [comment]
You need to install RediSearch. Using docker you can run the following

```
docker run -it --rm --name redis-search-2 \
   -p 6379:6379 \
   redislabs/redisearch:2.2.5
```

**Comment by CyberAmyntas** [comment]
Use Docker or install Redis with Redisearch - FT.Create (https://redis.io/commands/ft.create/)

**Comment by tylerhutcherson** [comment]
Hi just to clarify from the Redis side, you need to make sure both `RediSearch` and `RedisJSON` are installed. They come by default with the Redis Stack docker container we reference under: https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/docker/redis

This should fix your issues.

**Comment by tylerhutcherson** [comment]
We'll open a PR with a module check to return a clearer error. Stay tuned.

**Comment by Noah670** [comment]
Updating Docker fixed my issue

**Comment by isafulf** [comment]
addressed with:
https://github.com/openai/chatgpt-retrieval-plugin/pull/38
