### ISSUE TITLE
some part of the upsert file method doesn't work for windows

### ISSUE THREAD

**Issue by NICKLLM** [openai/chatgpt-retrieval-plugin#170]
The following code should be running fine on a Unix system, however when I tested them on my local Windows11 machine, there're constantly errors like "No Such File or Directory" or "Permission Denied". This is related to the code in services/file.py 

"""  temp_file_path = "/tmp/temp_file"  """

Because of differences in the format of folders between Unix and Windows, this line wouldn't work in Windows. 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/19790836/230967393-25cabd24-ccd2-4da4-ad7d-fea8618a6007.png">

With the help of GPT-4, I was able to solve the issue with following code.

import tempfile

    temp_file_path=os.path.join(os.path.dirname(os.path.realpath(__file__)), "temp")
    if not os.path.exists(temp_file_path):
        os.makedirs(temp_file_path)

    # Create a temporary file in the custom_directory
    temp_file = tempfile.NamedTemporaryFile(dir=temp_file_path, delete=False)

    # Write the file_stream to the temporary file
    with open(temp_file.name, "wb") as f:
        f.write(file_stream)

    try:
        extracted_text = extract_text_from_filepath(temp_file.name, mimetype)
    except Exception as e:
        print(f"Error: {e}")
        # Close the temporary file and remove it from the temp location
        temp_file.close()  # Add this line to close the temporary file
        os.remove(temp_file_path)
        raise e

    # Close the temporary file and remove it from the temp location
    temp_file.close()  # Add this line to close the temporary file
    # remove file from temp location
    os.remove(temp_file.name)

    return extracted_text

I also had some problem removing the file on my Windows machine, that's why that's a temp_file.close()

**Comment by zero469** [comment]
Why don't you merge this change into repo?

**Comment by NICKLLM** [comment]
> 

I was not really sure this is a good practice. I assume people would have better solution than this, I just wanted tell people that this part would have some problem on Windows machine
