### ISSUE TITLE
404 Not Found errors on Windows

### ISSUE THREAD

**Issue by jtbiddle** [openai/chatgpt-retrieval-plugin#174]
Hello, I've tried to install and run this using [this guide](https://betterprogramming.pub/enhancing-chatgpt-with-infinite-external-memory-using-vector-database-and-chatgpt-retrieval-plugin-b6f4ea16ab8) on my Windows 10 machine, both natively and using WSL with Ubuntu 22. 

When running natively on Windows, the IP address of 0.0.0.0 is unreachable, but is accessible through localhost but giving the error ```{"detail":"Not Found"}```.  If I find and replace all instances of 0.0.0.0 with 127.0.0.1, the error changes to ```{"detail":"Not authenticated"}```. and prints
 ```
INFO:     127.0.0.1:25439 - "GET / HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:25439 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

Running on Ubuntu in WSL (without any of the files changed), opening localhost:8000 shoes ```{"detail":"Not Found"}``` and the console prints ```INFO:     127.0.0.1:34498 - "GET / HTTP/1.1" 404 Not Found```.  I would like to open that port if this is a firewall issue, but the port is different every time I run the program. Running it locally with ```poetry run dev``` gives the same message and errors.

**Comment by tzoltan31** [comment]
You are probably missing your bearer_token for authorization

**Comment by jtbiddle** [comment]
I managed to fix this by using a new ChatGPT API token and using the ```upsert``` endpoint instead of ```upsert-file```. (And I don't know why I was testing it by loading the URL in a browser instead of calling the API, but I guess it worked to show the errors either way)

**Comment by rachaelw-usafacts** [comment]
having the same issue, what is the correct endpoint for `upsert` vs `upsert-file`
