### ISSUE TITLE
"POST /query HTTP/1.1" 500 Internal Server Error

### ISSUE THREAD

**Issue by alexwhen** [openai/chatgpt-retrieval-plugin#194]
i am using the qdrant vector database, and after successfully uploading a file, an error occurred when executing the query. 

Error: 3 validation errors for MatchValue
value
  value is not a valid boolean (type=value_error.strictbool)
value
  value is not a valid integer (type=type_error.integer)
value
  str type expected (type=type_error.str)
INFO:     127.0.0.1:50951 - "POST /query HTTP/1.1" 500 Internal Server Error

**Comment by af913337456** [comment]
@alexwhen  i got this error：

Error: Error parsing vector similarity query: query vector blob size (12288) does not match index's expected size (40).

**Comment by af913337456** [comment]
> @alexwhen i got this error：
> 
> Error: Error parsing vector similarity query: query vector blob size (12288) does not match index's expected size (40).

solved !

**Comment by k4pran** [comment]
It may help others to share your solutions rather than just saying it has been solved

**Comment by knoel99** [comment]
yes what was your solution plz
