### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by pelguetat** [openai/chatgpt-retrieval-plugin#200]
Hi,

I'm using Weaviate and when I try to query my db I'm getting the 500 internal server error, Error: None is not a valid Source. The upsert worked with no issues. 
This is the query:
`queries = [
    {'query': "¿Cuanto dura la jornada laboral?"},
   
]

res = requests.post(
    f"{endpoint_url}/query",
    headers=headers,
    json={
        'queries': queries
    }
)
res`
My OpenAI account does not have access to chatgpt plugins or gpt-4, so I'm wondering if that might be the problem. 

Thanks,

**Comment by knoel99** [comment]
did you find any solution?
