### ISSUE TITLE
Can I use this plugin while using openai's api?

### ISSUE THREAD

**Issue by Honst211** [openai/chatgpt-retrieval-plugin#231]
I have not applied for the official plug-in now, and I want to use this plug-in function when calling the api.

**Comment by pb30** [comment]
Plugins are only available through ChatGPT interface, not through the API (and not currently on their roadmap) [[1](https://community.openai.com/t/is-it-possible-to-utilize-a-plugin-with-the-chatgpt-api/141512/2?u=novaphil)]
