### ISSUE TITLE
Azure openai does NOT support batch embedding, is it possible to set EMBEDDINGS_BATCH_SIZE as a configurable parameter

### ISSUE THREAD

**Issue by zero469** [openai/chatgpt-retrieval-plugin#239]
I am using my Azure openai model to work with this plugin, but I found that I can't upsert the file. After some research I found out that this is caused by embedding, which I talked about in title. After I change EMBEDDINGS_BATCH_SIZE=1, everything is fine, so can anyone make this parameter configurable?

**Comment by nikhilpatange** [comment]
Here is a workaround for this issue, using the Huggingface sentence transformer with FAISS.

https://www.linkedin.com/pulse/navigating-langchain-overcoming-azure-openais-batching-nikhil-patange%3FtrackingId=R6BRjwdjRZadwJFtjwUzGg%253D%253D/?trackingId=R6BRjwdjRZadwJFtjwUzGg%3D%3D
