### ISSUE TITLE
Unable to Save Data Using ChatGPT Retrieval Plugin with Memory Enabled

### ISSUE THREAD

**Issue by tomherbin** [openai/chatgpt-retrieval-plugin#246]
I've followed the instructions on the [ChatGPT Retrieval Plugin with Memory GitHub page](https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/memory) to enable memory for the retrieval plugin. This involved copying the contents of openapi.yaml and ai-plugin.json from the example into the main files of the same names.

After enabling memory, I've been able to successfully perform queries. However, I'm encountering issues when trying to save data into my database through the plugin. Specifically, when I try to use prompts to save data, the plugin seems to treat these as queries instead of upsert operations.

Here's a screenshot of the issue I'm encountering:

![Screenshot 2023-05-14 at 08 23 20](https://github.com/openai/chatgpt-retrieval-plugin/assets/43685774/cee5c1d7-b853-4cbf-979b-38987679d957)

I'm looking for any tips or guidance on how to resolve this issue. Has anyone else encountered this problem and found a solution?

**Comment by tomherbin** [comment]
I always answer my questions when asking haha.

If you run into the same issue, you need to be aware of cache by going into private navigation when trying out your plugin and be sure of the openAPI file that is taken into account. Don't know why it's the local one on my side.

**Comment by cowile** [comment]
Is it just the browser cache you are talking about or something else? I am having a similar problem. ChatGPT does not seem to recognize its ability to upsert. I've tried clearing the browser cache and opening a private window but am getting the same problem.
