### ISSUE TITLE
redis.exceptions.ResponseError: Invalid rule type: JSON

### ISSUE THREAD

**Issue by semon2019** [openai/chatgpt-retrieval-plugin#26]
**this is my redis service:**
<img width="983" alt="image" src="https://user-images.githubusercontent.com/46260207/227468276-16edb8c7-e210-4e78-a136-a29174a319ce.png">

**this is the error when i use:  poetry run start**
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/46260207/227468617-5fca6eaa-8ccb-4d7f-9950-0bbf21987a9f.png">

**Comment by semon2019** [comment]
**this is the error:**
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/46260207/227468693-8eb487e6-1705-48ba-a025-09ff0c00fd86.png">

**Comment by Jarvan-via** [comment]
redis.exceptions.ResponseError: unknown command `FT.CREATE`, with args beginning with: `index`, `ON`, `JSON`, `PREFIX`, `1`, `doc`, `SCORE`, `1.0`, `SCHEMA`, `$.document_id`, `AS`, `document_id`, `TAG`, `SEPARATOR`,

**Comment by tylerhutcherson** [comment]
Hi @semon2019 As @AbirKorched pointed out, you need to make sure both `RediSearch` and `RedisJSON` are installed. They come by default with the docker container we reference under: https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/docker/redis

This should fix your issues.

**Comment by Spartee** [comment]
@tylerhutcherson we should implement the module check that we did for Langchain.

**Comment by deep55gariya** [comment]
you have to install RediSearch.

**Comment by semon2019** [comment]
> Hi @semon2019 As @AbirKorched pointed out, you need to make sure both `RediSearch` and `RedisJSON` are installed. They come by default with the docker container we reference under: https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/docker/redis
> 
> This should fix your issues.

thanks!!!

**Comment by Jarvan-via** [comment]
> @Jarvan-via you need to install RediSearch. You need to install RediSearch. Using docker you can run the following after moving under https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/docker/redis
> 
> docker compose up -d
 
thanks!  i hava soved this problem

**Comment by isafulf** [comment]
addressed with:
https://github.com/openai/chatgpt-retrieval-plugin/pull/38

**Comment by erikmackinnon** [comment]
> 

Thank you for sharing this, was driving me a bit nuts this morning. Just ended up running from docker as everyone else did, working well now.

**Comment by erikmackinnon** [comment]
> Hi @semon2019 As @AbirKorched pointed out, you need to make sure both `RediSearch` and `RedisJSON` are installed. They come by default with the docker container we reference under: https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/docker/redis
> 
> This should fix your issues.

Thank you for sharing this, was driving me a bit nuts this morning. Just ended up running from docker as everyone else did, working well now.
