### ISSUE TITLE
azure-search-documents install error

### ISSUE THREAD

**Issue by benjamin-kirkbride** [openai/chatgpt-retrieval-plugin#289]
I get the following error when trying to install:

```
ERROR: Could not find a version that satisfies the requirement azure-search-documents==1.0.0b4, 11.0.0, 11.1.0b1, 11.1.0b2, 11.1.0b3, 11.1.0b4, 11.1.0, 11.2.0b1, 11.2.0b2, 11.20b6, 11.3.0b7, 11.3.0b8, 11.3.0, 11.4.0b1, 11.4.0b2, 11.4.0b3)
ERROR: No matching distribution found for azure-search-documents==11.4.0a20230509004
```

**Comment by argenz** [comment]
I have the same problem. I have created a pip.ini file and installed the keyring artifacts-keyring packages but not wokring. Please help

**Comment by wanand** [comment]
I'm getting the same error. Is there a fix for this issue?

**Comment by cticevans** [comment]
same.

**Comment by cticevans** [comment]
if you are getting this when installing from a requirements.txt, i put this at the beginning and it solved my issue:
--extra-index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/

**Comment by dykim3** [comment]
> if you are getting this when installing from a requirements.txt, i put this at the beginning and it solved my issue: --extra-index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/

@cticevans  do you mean this? 
```
--extra-index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/ azure-search-documents==11.4.0a20230509004
```

**Comment by cticevans** [comment]
actually i just added the extra index location and pip found it there -- I didn't add the explicit package:

at top of requirements: --extra-index-url=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/

then requirement of: azure-search-documents==11.4.0a20230509004

**Comment by mukundhareddy1996** [comment]
I am also getting the same error 
 ERROR: Could not find a version that satisfies the requirement azure-search-documents==11.4.0a20230509004 (from versions: 1.0.0b2, 1.0.0b3, 1.0.0b4, 11.0.0, 11.1.0b1, 11.1.0b2, 11.1.0b3, 11.1.0b4, 11.1.0, 11.2.0b1, 11.2.0b2, 11.2.0b3, 11.2.0, 11.2.1, 11.2.2, 11.3.0b1, 11.3.0b2, 11.3.0b3, 11.3.0b4, 11.3.0b5, 11.3.0b6, 11.3.0b7, 11.3.0b8, 11.3.0, 11.4.0b1, 11.4.0b2, 11.4.0b3)
