### ISSUE TITLE
Problematic deployment size

### ISSUE THREAD

**Issue by Bartekkur1** [openai/chatgpt-retrieval-plugin#293]
Hey, I've spent past few days trying to deploy this plugin at azure as a web app. I tried two approaches but came into the same problem every time:

1.  Uploading docker image to container registry and running web app from it (size was around 7gb)
2. Running CI builds and running web app from artifact (size was around 5gb)

In each solution the application size is a issue that generates huge expenses in comparison to running it.
Most of the image size comes from nvidia drivers packages that is a torch dependency - is that really needed?
Am I doing something wrong with the builds? How are you guys building it and hosting it?

**Comment by masterkain** [comment]
if you wanna help testing https://github.com/icoretech/chatgpt-retrieval-plugin-docker

**Comment by Bartekkur1** [comment]
@masterkain just noticed your issue, will take a look for sure! :)

**Comment by Bartekkur1** [comment]
I came across [issue 240](https://github.com/openai/chatgpt-retrieval-plugin/issues/240) and decided to try removing some packages, after removing chromadb, qdrant-client, redis, pgvector from pyproject.toml (which I don't use anyway) I managed to reduce size to 1.2gb which is way less than that 7gb monster.

<img width="486" alt="image" src="https://github.com/openai/chatgpt-retrieval-plugin/assets/15158339/cff9c38c-9909-46a0-98a5-fcd5a5559a33">


I will be closing this issue as its solved for me, if you have similar problem just reduce the libraries that you don't use.
