### ISSUE TITLE
  clang: error: the clang compiler does not support '-march=native'    on poetry install            

### ISSUE THREAD

**Issue by gkibilov** [openai/chatgpt-retrieval-plugin#330]
(sgk-plugin-py3.10) gkibilov@Georges-MacBook-Pro sgkplugin % poetry install         
Installing dependencies from lock file

Package operations: 20 installs, 0 updates, 0 removals

  • Installing hnswlib (0.7.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_ext
  creating var
  creating var/folders
  creating var/folders/1p
  creating var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn
  creating var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpf0uy_ebb/.venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp_ylpagz7.cpp -o var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp_ylpagz7.o -std=c++14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpf0uy_ebb/.venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp0m2c3mq6.cpp -o var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp0m2c3mq6.o -fvisibility=hidden
  building 'hnswlib' extension
  creating build
  creating build/temp.macosx-10.9-universal2-cpython-310
  creating build/temp.macosx-10.9-universal2-cpython-310/python_bindings
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpf0uy_ebb/.venv/lib/python3.10/site-packages/pybind11/include -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpf0uy_ebb/.venv/lib/python3.10/site-packages/numpy/core/include -I./hnswlib/ -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpf0uy_ebb/.venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-310/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.0\" -std=c++14 -fvisibility=hidden
  clang: error: the clang compiler does not support '-march=native'
  error: command '/usr/bin/clang' failed with exit code 1
  

  at ~/Library/Python/3.9/lib/python/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with hnswlib (0.7.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "hnswlib (==0.7.0)"'.

(sgk-plugin-py3.10) gkibilov@Georges-MacBook-Pro sgkplugin % pip wheel --use-pep517 "hnswlib (==0.7.0)"
Collecting hnswlib==0.7.0
  Downloading hnswlib-0.7.0.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from hnswlib==0.7.0)
  Using cached numpy-1.25.0-cp310-cp310-macosx_10_9_x86_64.whl (20.1 MB)
Saved ./numpy-1.25.0-cp310-cp310-macosx_10_9_x86_64.whl
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/1p
      creating var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn
      creating var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/gkibilov/Library/Caches/pypoetry/virtualenvs/sgk-plugin-9OQ2lEda-py3.10/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpipqtqj7q.cpp -o var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmpipqtqj7q.o -std=c++14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/gkibilov/Library/Caches/pypoetry/virtualenvs/sgk-plugin-9OQ2lEda-py3.10/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp5qfffxak.cpp -o var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/tmp5qfffxak.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-310
      creating build/temp.macosx-10.9-universal2-cpython-310/python_bindings
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/pip-build-env-ka7xrqgo/overlay/lib/python3.10/site-packages/pybind11/include -I/private/var/folders/1p/wppj4l8x7j356pk05d_0j7f80000gn/T/pip-build-env-ka7xrqgo/overlay/lib/python3.10/site-packages/numpy/core/include -I./hnswlib/ -I/Users/gkibilov/Library/Caches/pypoetry/virtualenvs/sgk-plugin-9OQ2lEda-py3.10/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-310/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.0\" -std=c++14 -fvisibility=hidden
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Failed to build one or more wheels
(sgk-plugin-py3.10) gkibilov@Georges-MacBook-Pro sgkplugin %

**Comment by gkibilov** [comment]
(sgk-plugin-py3.10) gkibilov@Georges-MacBook-Pro sgkplugin % clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(sgk-plugin-py3.10) gkibilov@Georges-MacBook-Pro sgkplugin %

**Comment by kcho02** [comment]
Were you able to resolve the issue? I am facing the same

**Comment by gkibilov** [comment]
Sorry, did not get a chance to.

**Comment by kcho02** [comment]
`export HNSWLIB_NO_NATIVE=1` worked for me FYI

**Comment by gkibilov** [comment]
Thanks, I'll give it a try!
