### ISSUE TITLE
Query after upsert-file

### ISSUE THREAD

**Issue by magallardo** [openai/chatgpt-retrieval-plugin#37]
Hello,

I was able to call upsert-file with a pdf document and it returned successfully an id for the document. However, when I try to query I am getting a 500 Internal Server Error.

In the console running the plugin, I can see the following error:
Error: None is not a valid Source

In my query request I only provided the document_id in the filter section as the upsert-file operation does not allow to provide any other metadata.

Could you please advise how to query when the documents are added using  upsert-file. 

Thanks,
Marcelo

**Comment by hardbyte** [comment]
I'm getting the same with the Weaviate provider

**Comment by CyberAmyntas** [comment]
> Hello,
> 
> I was able to call upsert-file with a pdf document and it returned successfully an id for the document. However, when I try to query I am getting a 500 Internal Server Error.
> 
> In the console running the plugin, I can see the following error: Error: None is not a valid Source
> 
> In my query request I only provided the document_id in the filter section as the upsert-file operation does not allow to provide any other metadata.
> 
> Could you please advise how to query when the documents are added using upsert-file.
> 
> Thanks, Marcelo

For the time being, when you query use the filter, source = "file" to query correctly until this is resolved.

```
{
  "queries": [
    {
      "query": "string",
      "filter": {
        "source": "file"
      },
      "top_k": 5
    }
  ]
}
```

**Comment by isafulf** [comment]
Thank you all!
Resolved here: https://github.com/openai/chatgpt-retrieval-plugin/commit/e07ffedb3f0365c3839b3681cc3781174634f471

**Comment by olaf-hoops** [comment]
> Hello,
> 
> I was able to call upsert-file with a pdf document and it returned successfully an id for the document. However, when I try to query I am getting a 500 Internal Server Error.
> 
> In the console running the plugin, I can see the following error: Error: None is not a valid Source
> 
> In my query request I only provided the document_id in the filter section as the upsert-file operation does not allow to provide any other metadata.
> 
> Could you please advise how to query when the documents are added using upsert-file.
> 
> Thanks, Marcelo

Hi Marcelo,
I'm currently trying to upsert a pdf file but I'm stuck. Always getting "Internal Server Error".
I can't seem to find proper documentation how to do it right. It would be really kind if you could show me a little code example how you uperserted a file properly.
Thank, Olaf
