### ISSUE TITLE
404s when using the pinecone example

### ISSUE THREAD

**Issue by JacobGoldenArt** [openai/chatgpt-retrieval-plugin#57]
Hello, 
I've gone through all the setup steps and using the pinecone example I've been able to have the script set up my pinecone index. I then set up the app on Digital Ocean (I also tried this locally using Poetry with the same results). I download the dataset and prepare it, then comes the issue:
When I try to post to the API, Using this code: 

```
from tqdm.auto import tqdm 
import requests
from requests.adapters import HTTPAdapter, Retry
batch_size = 100
endpoint_url = "https://seashell-app-nhcyq.ondigitalocean.app/"
s = requests.Session()
# we setup a retry strategy to retry on 5xx errors
retries = Retry(
total=5, # number of retries before raising error
backoff_factor=0.1,
status_forcelist=[500, 502, 503, 504]
)
s.mount('http://', HTTPAdapter(max_retries=retries))
for i in tqdm(range(0, len(documents), batch_size)):
i_end = min(len(documents), i+batch_size)
# make post request that allows up to 5 retries
res = s.post(
f"{endpoint_url}/upsert",
headers=headers,
json={
"documents": documents[i:i_end]
}
)
```

I'm seeing a long list of 404 messages like this: [chatgpt-retrieval-plugin] [2023-03-26 17:25:41] INFO: 10.244.15.94:41594 - "POST //upsert HTTP/1.1" 404....(lots more like this)

So I don't think my initial post request is working properly.

Then I run the Queries Code Blocks:
```
queries = data['question'].tolist()
# format into the structure needed by the /query endpoint
queries = [{'query': queries[i]} for i in range(len(queries))]
len(queries)
res = requests.post(
"https://seashell-app-nhcyq.ondigitalocean.app/query",
headers=headers,
json={
'queries': queries[:5]
}
)
res
```

```
for query_result in res.json()['results']:
query = query_result['query']
answers = []
scores = []
for result in query_result['results']:
answers.append(result['text'])
scores.append(round(result['score'], 2))
print("-"*70+"\n"+query+"\n\n"+"\n".join([f"{s}: {a}" for a, s in zip(answers, scores)])+"\n"+"-"*70+"\n\n")
```

Output is:
----------------------------------------------------------------------
To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?
----------------------------------------------------------------------
----------------------------------------------------------------------
When did the Scholastic Magazine of Notre dame begin publishing?
----------------------------------------------------------------------
----------------------------------------------------------------------

So although I see my queries. I don't get back any answers from the data set. Any help much appreciated!

**Comment by justjoehere** [comment]
I’m too getting 404 on the upset, but can’t figure out what’s wrong.  What did you find?
