### ISSUE TITLE
Query Redis backend fail with 'NewConnectionError'

### ISSUE THREAD

**Issue by nayutah** [openai/chatgpt-retrieval-plugin#68]
1, Configure a redis DATASTORE (
- 9e6f17fc09d3 is the container id of chatgpt-retrieval-plugin
- 192.168.2.159 is the ip address of my MacBook Pro
- env list about redis
root@9e6f17fc09d3:~# env | grep -i redis
REDIS_HOST=192.168.2.159
DATASTORE=redis
REDIS_PORT=6379
- Telnet is OK in chatgpt-retrieval-container
root@9e6f17fc09d3:~# telnet 192.168.2.159 6379
Trying 192.168.2.159...
Connected to 192.168.2.159.
Escape character is '^]'.
^]

2, upsert an email like this
{
  "documents": [
    {
      "id": "123456",
      "text": "my first email",
      "metadata": {
        "source": "email",
        "source_id": "111111",
        "url": "string",
        "created_at": "2023-3-26::10:00:00",
        "author": "tom"
      }
    }
  ]
}

3, plugin log
INFO:     172.17.0.1:63002 - "POST /upsert HTTP/1.1" 500 Internal Server Error
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9e380c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /v1/embeddings
............ 4 duplicated lines is omitted ............
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9e382620>: Failed to establish a new connection: [Errno 111] Connection refused')': /v1/embeddings
Error: RetryError[<Future at 0xffff9e382980 state=finished raised APIConnectionError>]
INFO:     172.17.0.1:65224 - "POST /upsert HTTP/1.1" 500 Internal Server Error

**Comment by FJJLeon** [comment]
I have the same problem, have you solved it?
Is it seems an issue with the API key, network, or authentication?

**Comment by nayutah** [comment]
Not yet, I will drill down to it in spare time. I guess it is about the HTTP module, has nothing to do with Redis.

**Comment by CyberAmyntas** [comment]
Can you try the cli for redis?

`redis-cli monitor` - If this connects from the same subnet/machine as your machine `192.168.2.159 `, then the issue is outside of redis.

The next step is to understand the issues related to `/v1/embeddings` and how you are accessing it, as the IP seems to be outside of your current range `172.17.0.1`

**Comment by nayutah** [comment]
> Can you try the cli for redis?
> 
> `redis-cli monitor` - If this connects from the same subnet/machine as your machine `192.168.2.159 `, then the issue is outside of redis.
> 
> The next step is to understand the issues related to `/v1/embeddings` and how you are accessing it, as the IP seems to be outside of your current range `172.17.0.1`

redis-cli works well in my Mac, I use the 'upsert' function through  the FastAPI web portal, '/v1/embeddings' comes up in the error essage.

**Comment by leslie0912** [comment]
> > 你能试试redis的cli吗？
> > `redis-cli monitor`- 如果这与您的机器连接自同一子网/机器`192.168.2.159 `，则问题出在 redis 之外。
> > 下一步是了解与之相关的问题`/v1/embeddings`以及您如何访问它，因为 IP 似乎超出了您当前的范围`172.17.0.1`
> 
> redis-cli 在我的 Mac 上运行良好，我通过 FastAPI 门户网站使用“upsert”功能，“/v1/embeddings”出现在错误消息中。

use proxy

**Comment by nayutah** [comment]
> I have the same problem, have you solved it? Is it seems an issue with the API key, network, or authentication?

It is a network problem to reach https://api.openai.com/v1/embeddings , so fix it with a proxy or deploy the plugin where the network reachable.

**Comment by isafulf** [comment]
This is now resolved, thanks all cc @tylerhutcherson
