### ISSUE TITLE
upsert-file API does not store DocumentMetadata.source as 'file'

### ISSUE THREAD

**Issue by SML0127** [openai/chatgpt-retrieval-plugin#75]
When I upload a file using the upsert-file API in UI (http://localhost:8000/docs), 
the `DocumentMetadata.source` is set to None.

As a result, the uploaded file is not retrieved because the source is `None` when querying.

For testing, I change `get_document_from_file` in services/file.py like below
```python
async def get_document_from_file(file: UploadFile) -> Document:
    extracted_text = await extract_text_from_form_file(file)
    print(f"extracted_text:")
    # get metadata
    metadata = DocumentMetadata()
    metadata.source="file" # added for testing
    doc = Document(text=extracted_text, metadata=metadata)
    print(doc)
    return doc
```

It's works.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/13589283/227913258-4ddf5fb7-a1a1-4833-800d-b5da78727c4e.png">

FYI
OS: ubuntu 20.04 5.4.0-146-generic
DATASTORE: redis

**Comment by SML0127** [comment]
This issue related to this PR(https://github.com/openai/chatgpt-retrieval-plugin/pull/32)

**Comment by isafulf** [comment]
Thank you all!
Resolved here: https://github.com/openai/chatgpt-retrieval-plugin/commit/e07ffedb3f0365c3839b3681cc3781174634f471
