### ISSUE TITLE
grpcio takes very long time (python 3.11 in fedora f37)

### ISSUE THREAD

**Issue by giuliohome** [openai/chatgpt-retrieval-plugin#90]
Maybe due to the fact that I have done

`poetry env use python3.11`

but [grpcio is building from source](https://github.com/grpc/grpc/issues/22815#issuecomment-1487392645) and takes forever...

**Comment by giuliohome** [comment]
I've tried a` poetry lock` just now after updating `python = "^3.11"` in `pyproject.toml`... but still no luck, it wants to downgrade grpcio and resort to building... (will keep this comment edited if I manage to sort it out by myself)

**Comment by filip-halt** [comment]
Pymilvus is in the process of getting updated to support 3.11. For now, if you are not using Milvus/Zilliz, I recommend removing pymilvus from the poetry install.

**Comment by giuliohome** [comment]
Thank you for the fast feedback. Yes, I'm actually using Milvus/Zilliz, but I have one or maybe two options: choosing a machine with python 3.10 or finding an alternative to Milvus/Zilliz (if possible).
Feel free to close the issue or keep open as you deem correct.

**Comment by giuliohome** [comment]
@filip-halt ok, I'll follow your idea and I'll try to proceed maybe with a Redis datastore instead of Milvus/Zilliz on this machine having pyton 3.11, thanks.

**Comment by dooleyb1** [comment]
@giuliohome Did you manage to resolve the above? I'm experiencing the same when doing `poetry install` on M1 Mac 11.4 running python 3.10

**Comment by giuliohome** [comment]
@dooleyb1 hi! I managed to solve the issue but I've not understood what you are experiencing. If you say python 3.10 all should be fine, maybe please add more details about your problem
