### ISSUE TITLE
Running in docker showing error that DATASTORE not found

### ISSUE THREAD

**Issue by akrabulislam** [openai/chatgpt-retrieval-plugin#96]
I have added all the required variables for `DATASTORE`

I used 'pinecone' as a `DATASTORE` and added all the required variables for pinecone.

This is how I run in the docker

- docker build -t python-project-with-docker .
- docker run -d --env-file ./.env -p 8000:8000 python-project-with-docker 

But getting this error. I tried with several other vector stores but it's showing the same problem.

![WM-Screenshots-20230329154457](https://user-images.githubusercontent.com/24622737/228495280-b8d018c8-2649-41ad-97b2-5607218c6be5.png)

I am using Windows 10.

**Comment by yosinem** [comment]
try set the envierment varieble without the "".
